name: 'sqlbot'
version: '1.0.0'
config-version: 2

# This dbt project is used for SQLBot integration tests
# It provides a minimal dbt environment for testing database queries

profile: 'Sakila'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  sqlbot:
    # Configs can be applied to any path in the model hierarchy
    materialized: view

# Basic project structure for SQLBot testing environment